name = "gsg"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

[pages]
  project_name = "gsg"
  build_command = "npm run build"
  destination_dir = "dist"

[[d1_databases]]
  binding = "DB"
  database_name = "gsg"
  database_id = "${D1_DATABASE_ID}"

[[kv_namespaces]]
  binding = "OTP_KV"
  id = "${OTP_KV_ID}"

[[kv_namespaces]]
  binding = "SESSION_KV"
  id = "${SESSION_KV_ID}"

[vars]
  ORIGIN = "${ORIGIN_URL}"
  TURNSTILE_SECRET = "${TURNSTILE_SECRET}"
  EMAIL_API_KEY = "${EMAIL_API_KEY}"
  LUCIA_SESSION_SECRET = "${LUCIA_SESSION_SECRET}"
  ADMIN_API_KEY = "${ADMIN_API_KEY}"
